version: '3.8'

services:
  bot:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - keydb

  keydb:
    image: eqalpha/keydb:latest
    ports:
      - "6379:6379"
    volumes:
      - keydb_data:/data

volumes:
  keydb_data:
